import { NextRequest, NextResponse } from 'next/server';
import { cleanAccountId } from '@/lib/stripe';
import { validateAccountToken } from '@/lib/accountAuth';
import { verifyConnection, CanvasApiError } from '@/lib/canvasApi';
import { saveCanvasConnection } from '@/lib/canvasConnection';

export const dynamic = 'force-dynamic';

const CORS = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' };
export async function OPTIONS() { return new NextResponse(null, { status: 204, headers: CORS }); }

// Connects a teacher's Canvas account by verifying their personal access token against
// GET /users/self, then storing it encrypted. This token is self-generated by the teacher
// from their own Canvas Settings page — no school/IT approval involved.
export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null);
  const accountId = cleanAccountId(body?.accountId);
  if (!accountId) return NextResponse.json({ error: 'Missing account.' }, { status: 400, headers: CORS });

  const verified = await validateAccountToken(accountId, body?.accountToken);
  if (!verified) return NextResponse.json({ error: 'Could not verify this account. Reload the page and try again.' }, { status: 403, headers: CORS });

  const domain = String(body?.domain || '').trim();
  const token = String(body?.token || '').trim();
  if (!domain || !token) return NextResponse.json({ error: 'Canvas domain and API token are both required.' }, { status: 400, headers: CORS });

  try {
    const user = await verifyConnection(domain, token);
    await saveCanvasConnection(accountId, domain, token, user.name || '');
    return NextResponse.json({ ok: true, userName: user.name || '', domain }, { headers: CORS });
  } catch (error) {
    const status = error instanceof CanvasApiError ? error.status : 500;
    const message = error instanceof Error ? error.message : 'Could not connect to Canvas.';
    return NextResponse.json({ error: message }, { status: status === 401 ? 401 : 502, headers: CORS });
  }
}
